const industries = [
  'Administrative Services',
  'Advertising',
  'Agriculture and Farming',
  'Apps',
  'Artificial Intelligence',
  'Biotechnology',
  'Clothing and Apparel',
  'Commerce and Shopping',
  'Consumer Electronics',
  'Consumer Goods',
  'Content and Publishing',
  'Data and Analytics',
  'Design',
  'Education',
  'Energy',
  'Events',
  'Financial Services',
  'Food and Beverage',
  'Gaming',
  'Government and Military',
  'Health Care',
  'Information Technology',
  'Internet Services',
  'Lending and Investments',
  'Manufacturing',
  'Media and Entertainment',
  'Messaging and Telecommunications',
  'Mobile',
  'Music and Audio',
  'Natural Resources',
  'Navigation and Mapping',
  'Payments',
  'Platforms',
  'Privacy and Security',
  'Professional Services',
  'Real Estate',
  'Sales and Marketing',
  'Science and Engineering',
  'Software',
  'Sports',
  'Sustainability',
  'Transportation',
  'Travel and Tourism',
  'Video',
  'Other'
];

export default industries;
